apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-02j6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-02j6
    app.kubernetes.io/part-of: test-app-167662705
  name: devfile-sample-code-with-quarkus-02j6
  namespace: skhileri-tenant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-02j6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-02j6
    spec:
      containers:
      - env:
        - name: secondEnvVar
          value: "3000"
        image: quay.io/redhat-appstudio/user-workload@sha256:614799020d2f6c19a326e13187730e07e6dc677ca654bc84788f55c903397076
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 2Gi
status: {}
